version: '3.8'
services:
  pixis_ads_api_clean_and_load_entities:
    container_name: pixis_ads_api_clean_and_load_entities
    build:
      context: ../../
      dockerfile: ./amazon-ads-api/CleanAndLoadEntities/Dockerfile
    ports:
      - "9013:8080"
    env_file:
      - ./.env
    extra_hosts:
      - "dockerhost:127.0.0.1"
