version: '3.8'
services:
  pixis_ads_api_clean_and_load:
    container_name: pixis_ads_api_clean_and_load
    build:
      context: ../../
      dockerfile: ./amazon-ads-api/CleanAndLoad/Dockerfile
    ports:
      - "9011:8080"
    env_file:
      - ./.env
    extra_hosts:
      - "dockerhost:127.0.0.1"
