version: '3.8'
services:
  pixis_ads_api_create_table:
    container_name: pixis_ads_api_create_table
    build:
      context: ../../
      dockerfile: ./amazon-ads-api/CreateTable/Dockerfile
    ports:
      - "9012:8080"
    extra_hosts:
      - "dockerhost:127.0.0.1"
