version: '3.8'
services:
  queue_worker_scaling:
    container_name: queue_worker_scaling
    build:
      context: ../
      dockerfile: ./queue-worker-scaling/Dockerfile
    volumes:
      - ./:/var/task
    ports:
      - "9002:8080"
    env_file:
      - ./.env
    extra_hosts:
      - "dockerhost:127.0.0.1"
